---
# Ryan Cheevers-Brown, 2022-09-09, rfc6058@rit.edu
- hosts: redteam
  become: true

  tasks:
    - name: "test reachability"
      ping:

    - name: "Install nginx"
      apt: name=nginx update_cache=yes state=latest force_apt_get=yes
    
    - name: "Install python3"
      apt: name=python3 update_cache=yes state=latest force_apt_get=yes
    
    - name: "Install powershell empire"
      apt: name=powershell-empire update_cache=yes state=latest force_apt_get=yes

    - name: "Install metasploit"
      apt: name=metasploit update_cache=yes state=latest force_apt_get=yes