# Anthony Swierkosz (ajs2576)
# Install and configure a simple fake Minecraft hosting website using IIS.
---
- name: Install and Configure IIS
  hosts: iisservers

  tasks:

    - name: Test Reachability
      ansible.windows.win_ping:

    # Install the IIS Web-Server feature
    # Include sub features and the management tools
    - name: Install IIS
      ansible.windows.win_feature:
        name: Web-Server
        state: present
        include_sub_features: yes
        include_management_tools: yes
      register: win_feature

    # Reboot the system if the new feature needs a reboot to work
    - name: Reboot If Required
      ansible.windows.win_reboot:
      when: win_feature.reboot_required

    - name: Copy Website Over
      ansible.windows.win_copy:
        src: minecraft_server
        dest: C:\sites

    - name: Add Minecraft Hosting site to IIS
      community.windows.win_iis_website:
        name: Minecraft Hosting
        state: restarted
        port: 80
        ip: '*'
        application_pool: Minecraft Hosting
        physical_path: C:\sites\minecraft_server
        parameters: logfile.directory:C:\sites\logs

      # Remove Default Web Site and the standard port 80 binding
    - name: Remove Default Web Site
      community.windows.win_iis_website:
        name: "Default Web Site"
        state: absent